# Proyecto 2: Primera parte
Curso Ingeniería de Características


**Estephania Pivac Alcaraz**

---

**Problema de interés:**
Estudar la relación que existe entre la cantidad de accidentes de tránsito y la inversión a la conservación de carreteras.

## EDA
Análisis exploratiorio de datos

In [1]:
# Instalamos Pandas-profiling
#pip install Pandas-Profiling

# Importamos algunas librerías que vamos a necesitar
import os  # Para manejo de archivos y directorios
import urllib.request # Una forma estandard de descargar datos
# import requests # Otra forma no de las librerías de uso comun

import datetime # Fecha de descarga
import pandas as pd # Solo para ver el archivo descargado
import zipfile # Descompresión de archivos
import numpy as np
from pandas_profiling import ProfileReport

Abrimos los dataframe tidy que generamos en el proyecto 1.

In [2]:
# Generamos el dataframe de accidentes
tidy_accidentes = pd.read_csv("tidy_accidentes.csv", index_col=False)

# Convertimos cada variable de acuerdo a su tipo
# Categoricas
tidy_accidentes = tidy_accidentes.astype({'TIPACCID':'category', 'CAUSAACCI':'category', 'CAPAROD':'category', 'CLASACC':'category', 'EDAD':'category'})

# Fechas
#tidy_accidentes['FECHA'] = pd.to_datetime(tidy_accidentes['FECHA'], format='%m/%d/%Y', errors='coerce')
tidy_accidentes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81848 entries, 0 to 81847
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID_ENTIDAD  81848 non-null  int64
 1   ANIO        81848 non-null  int64
 2   TIPACCID    81848 non-null  category
 3   CAUSAACCI   81848 non-null  category
 4   CAPAROD     81848 non-null  category
 5   CLASACC     81848 non-null  category
 6   FECHA       81848 non-null  object
 7   EDAD        81848 non-null  category
dtypes: category(5), int64(2), object(1)
memory usage: 2.3+ MB

In [3]:
# Generamos el dataframe de conservación
tidy_conservacion = pd.read_csv("tidy_conservacion.csv", index_col=False)
tidy_conservacion

,ID_ENTIDAD,ENTIDAD,TOTAL_CONSERVACION,PROGRAMA_CONSERVACION
0,9,CIUDAD DE MEXICO,1.294363e+08,Estudios y/o Proyectos
1,9,CIUDAD DE MEXICO,1.091483e+08,Programa Asociación Público Privada de Conserv...
2,9,CIUDAD DE MEXICO,4.997081e+07,Programa Asociación Público Privada de Conserv...
3,9,CIUDAD DE MEXICO,8.514464e+07,Programa Asociación Público Privada de Conserv...
4,9,CIUDAD DE MEXICO,2.415727e+07,Programa Asociación Público Privada de Conserv...
...,...,...,...,...
1854,32,ZACATECAS,6.094561e+06,Conservación Rutinaria
1855,32,ZACATECAS,5.716601e+06,Conservación Rutinaria
1856,32,ZACATECAS,1.633732e+06,Otros Subprogramas
1857,32,ZACATECAS,2.625802e+06,Otros Subprogramas
1858,32,ZACATECAS,2.625802e+06,Otros Subprogramas

In [4]:
# Generamos el dataframe de suma estatal
tidy_suma_estatal = pd.read_csv("tidy_suma_estatal.csv", index_col=False)
tidy_suma_estatal

,ID_ENTIDAD,Total_accidentes,TIPACCID_Colisión con objeto fijo,TIPACCID_Colisión con vehículo automotor,TIPACCID_Salida del camino,TIPACCID_Volcadura,CAUSAACCI_Mala condición del camino,CLASACC_Fatal,CLASACC_Sólo daños,TOTAL_CONSERVACION,Total_programas
0,1,1222,130,449,340,80,30,86,696,2.488337e+08,32
1,2,489,97,271,30,28,1,19,342,5.620804e+08,54
2,3,93,3,55,5,24,5,4,59,6.243666e+08,58
3,4,559,34,119,231,48,50,52,325,5.237085e+08,37
4,5,466,59,151,64,131,33,30,348,5.600496e+08,41
5,6,1852,103,847,437,159,142,42,1160,2.634863e+08,26
6,7,2492,342,906,500,219,5,214,1604,1.004166e+09,90
7,8,3674,391,1471,547,814,225,167,2697,8.046833e+08,69
8,9,6,1,4,0,1,0,1,3,6.663901e+08,11
9,10,1103,90,440,69,285,24,63,730,6.134141e+08,86
10,11,4074,354,1571,555,634,86,189,2337,9.657767e+08,35
11,12,1699,184,505,416,371,96,53,1299,8.148538e+08,65
12,13,963,66,580,140,64,5,43,758,6.241780e+08,39
13,14,8400,680,4069,596,1573,146,412,6263,8.474364e+08,93
14,15,2551,355,1392,228,232,8,114,1859,7.021100e+08,61
15,16,8417,823,3275,1175,1620,511,349,5492,1.028365e+09,92
16,17,4535,353,1577,1009,613,163,107,2799,3.645993e+08,37
17,18,1212,146,355,332,126,25,66,729,4.165339e+08,50
18,19,3441,421,1696,455,469,76,75,2883,6.757206e+08,59
19,20,1543,146,510,359,228,12,61,1035,1.085570e+09,76
20,21,4252,558,1508,1161,437,9,432,3431,6.937462e+08,49
21,22,5771,962,2604,1589,283,65,139,4965,3.776753e+08,49
22,23,677,34,199,237,67,71,41,395,3.850145e+08,35
23,24,3339,612,1463,286,494,23,186,2620,8.114495e+08,62
24,25,2616,150,664,654,113,114,368,747,5.010197e+08,93
25,26,1980,137,593,253,513,150,156,1214,6.530741e+08,69
26,27,802,85,281,277,2,0,19,664,9.154680e+08,52
27,28,1765,102,556,210,685,74,117,837,8.569951e+08,101
28,29,2038,316,929,300,294,28,115,1542,5.915551e+08,48
29,30,6592,899,2710,1384,492,17,265,4296,1.048298e+09,99
30,31,1336,159,316,307,99,70,49,699,4.523249e+08,40
31,32,1889,165,590,471,352,48,245,987,6.214318e+08,51

In [5]:
# Generamos el dataframe de suma estatal
tidy_budget = pd.read_csv("budget_transparency.csv", index_col=False)
tidy_budget

,State ID,State,Year,Expenses Type ID,Expenses Type,Amount Approved
0,1,Aguascalientes,2013,8,Gasto de Obra Pública,1511908040
1,1,Aguascalientes,2014,8,Gasto de Obra Pública,1865135779
2,1,Aguascalientes,2015,8,Gasto de Obra Pública,1659723400
3,1,Aguascalientes,2016,8,Gasto de Obra Pública,1717532284
4,1,Aguascalientes,2017,8,Gasto de Obra Pública,1230564370
...,...,...,...,...,...,...
283,32,Zacatecas,2017,8,Gasto de Obra Pública,1992505733
284,32,Zacatecas,2018,8,Gasto de Obra Pública,2284882371
285,32,Zacatecas,2019,8,Gasto de Obra Pública,2567673138
286,32,Zacatecas,2020,8,Gasto de Obra Pública,2010497486
287,32,Zacatecas,2021,8,Gasto de Obra Pública,1084559922

In [5]:
prof = ProfileReport(tidy_suma_estatal)
prof.to_file(output_file='tidy_suma_estatal.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]